name: 'Build site'

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: run build script
        run: ./scripts/build.sh -u build-test

      - name: save artifact
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: /app/public/
