name: 'Build site'

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: run build script
        run: ./bin/build.sh -u build-test
